### ISSUE TITLE
Added conda package

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/eko#104]
Added a conda recipe to `conda-forge`

https://github.com/conda-forge/staged-recipes/pull/18289

Looks straightforward enough so I guess it will be part of conda-forge soon as soon as it is reviewed (I haven't pinged anyone yet because I'm waiting for the tests, ran only the Linux one in docker in my own computer).

**Comment by scarlehoff** [comment]
@andreab1997 once that is added to conda forge we will be able to merge https://github.com/NNPDF/nnpdf/pull/1537

**Comment by scarlehoff** [comment]
@AleCandido can the `banana` dependency be dropped? I don't understand why should eko depend on a package to benchmark against apfel. Shouldn't the `data` directory be part of ekobox?

**Comment by AleCandido** [comment]
`eko` is a unique distribution package, containing three distinct python packages: `eko`, `ekomark`, and `ekobox`.

The dependencies listed are required to be there, even though the installation of `ekomark` and `ekobox` is optional (in the sense that they are allowed not to work, because their dependencies are optional).

So, `banana` is already optional, but no, we cannot drop.

**Comment by scarlehoff** [comment]
I will need `ekobox` for what @andreab1997 is doing, which means I need `banana` right?

Btw, how do I not install `ekomark` and `ekobox`? `pip install .` will install all three regardless.

**Comment by AleCandido** [comment]
`pip install .` will install everything, but as written above, "they are allowed not to work".

Installing in python means copying some files somewhere, if you don't need, you can avoid `import` and nothing bad will happen (if you install only `eko` dependencies, `import eko` will work perfectly smooth, not everything else).

If you need `ekobox`, then you genuinely need `banana` (`ekobox` -> `ekomark` -> `banana`, and sometimes even directly), so there is no way out.

**Comment by scarlehoff** [comment]
Damn. Ok, then I will need more conda packages.

Does `banana` depend on `lhapdf` or `apfel`?

**Comment by AleCandido** [comment]
There is no `apfel` package on PyPI, and we do not depend on nothing that can not be installed by `pip`.

But you have bad luck: `banana` already depends on the temporary package I made for [`lhapdf`](https://pypi.org/project/a3b2bbc3ced97675ac3a71df45f55ba/) on PyPI.
In some sense I'm not very happy, since that package has various problems (not writing `lhapdf.conf` in the environment, that is instead required to work, apparently not running on M1), but I'm not yet sure I should give up completely...

If you need, even temporary, that dependency can be dropped.

**Comment by AleCandido** [comment]
P.S.: actually is everywhere: even `ekobox` depend directly on it, not only through `banana`
https://github.com/N3PDF/eko/blob/341e6323e680d2320ae4400da61c92a445160416/pyproject.toml#L54

**Comment by scarlehoff** [comment]
Oh no.

**Comment by scarlehoff** [comment]
(┛ಸ_ಸ)┛彡┻━┻

Let's talk on Monday to see whether there's a way we can go around this.

**Comment by scarlehoff** [comment]
Ok, added recipe for banana as well (same PR) https://github.com/conda-forge/staged-recipes/pull/18289 and @zaharid added LHAPDF https://github.com/conda-forge/staged-recipes/pull/18315 so we should be good to go.

Once @scarrazza adds also pineappl we have everything in conda.

@AleCandido could you give me a more external-friendly description for banana, I feel what I use is too short (and would only be understood by us) https://github.com/conda-forge/staged-recipes/blob/d18edfe9f43cefddc774103d6011f95a3b62539a/recipes/banana/meta.yaml#L49

**Comment by scarrazza** [comment]
> Once @scarrazza adds also pineappl we have everything in conda.

It is already in conda-forge and updated.

**Comment by AleCandido** [comment]
> @AleCandido could you give me a more external-friendly description for banana, I feel what I use is too short (and would only be understood by us) https://github.com/conda-forge/staged-recipes/blob/d18edfe9f43cefddc774103d6011f95a3b62539a/recipes/banana/meta.yaml#L49

Yes, let me think a moment. Even though it's more or less true, but I would replace `eko` and `yadism` with DIS and evolution codes.

**Comment by AleCandido** [comment]
@scarlehoff I saw the updated description, for me is good enough :)

**Comment by scarlehoff** [comment]
This can be closed:

https://github.com/conda-forge/eko-feedstock

**Comment by felixhekhorn** [comment]
I've added the conda badge - shall we also add the AUR badge?
