### ISSUE TITLE
backward evolution

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/eko#44]
see also discussion at https://lists.cam.ac.uk/mailman/private/ucam-nnpdf/2020-April/msg00016.html

a see at least two different ways on how to do this:
- evolve from `Q0 -> Q1` and invert the matrix (numerically?)
- do true backward evolution which changing kernels

**Comment by Zaharid** [comment]
I don't believe inverting the matrix works: `\Gamma` is a linear operator rather than a matrix and that cannot be inverted in the same way. In particular you can always sample a sufficiently dense grid that the matrix cannot be inverted in a stable way. Conversely if the grid is not dense enough there is the question of how good the approximation is (which for inverse problems, by default means bad).

**Comment by AleCandido** [comment]
Since in N space it's really a simple (vectorial) first order differential equation, once we have the solution evolving forward or backward makes no difference, no need to invert the matrix.

Instead we have one problem with intrinsic objects:
- we are able to evolve in one flavor patch
- we need to match the basis at thresholds, converting a charm in the flavor basis to its contribution at evolution basis

At the moment it has been designed to be done forward, and so contribution from c+ to the singlet, `S.c+`, is simply added to `S.S` and `S.g`.
Doing backward evolution instead require the decomposition from a "full flavor basis" (with for example 4 light quarks) in the mixed basis (evolution 3 flavors + 1 flavor in flavor basis, the so called *~~weird~~ intrinsic basis*).
This decomposition is perfectly possible and easy to be thought in the flavor basis (I'd simply need to recombine evolution ingredients to make the charm), but should be taken into account, while the current forward strategy does not apply.
